{% set version = "0.6" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-fastmatrix
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/fastmatrix_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/fastmatrix/fastmatrix_{{ version }}.tar.gz
  sha256: 3dcb93bd627b4d574e7d9400fd076c42e7b4849b1561a1f9d72b4dc6d456c2e8

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('fortran') }}        # [not win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - libblas                      # [not win]
    - liblapack                    # [not win]
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('fastmatrix')"           # [not win]
    - "\"%R%\" -e \"library('fastmatrix')\""  # [win]

about:
  home: https://faosorios.github.io/fastmatrix/
  license: GPL-3.0-only
  summary: Small set of functions to fast computation of some matrices and operations useful in statistics.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: fastmatrix
# Type: Package
# Title: Fast Computation of some Matrices Useful in Statistics
# Version: 0.2-357
# Date: 2020-09-17
# Authors@R: c(person(given = "Felipe", family = "Osorio", role = c("aut", "cre"), email = "felipe.osorios@usm.cl", comment = c(ORCID = "0000-0002-4675-5201")), person(given = "Alonso", family = "Ogueda", role = "aut", email = "alonso.ogueda@gmail.com"))
# Author: Felipe Osorio [aut, cre] (<https://orcid.org/0000-0002-4675-5201>), Alonso Ogueda [aut]
# Maintainer: Felipe Osorio <felipe.osorios@usm.cl>
# Description: Small set of functions to fast computation of some matrices and operations useful in statistics.
# Depends: R(>= 3.5.0)
# License: GPL-3
# URL: https://faosorios.github.io/fastmatrix/
# NeedsCompilation: yes
# LazyLoad: yes
# Packaged: 2020-09-17 20:46:59 UTC; felipe
# Repository: CRAN
# Date/Publication: 2020-09-18 07:50:02 UTC
